input {
  tcp {
    port => 5060
    codec => json
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movie-api-logs"
  }

  stdout {
    codec => rubydebug
  }

}