spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/movie_project
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8080
spring.security.user.name=khiem
spring.security.user.password=123456
#openssl rand -base64 64
#config JWT
khiem.jwt.base64-secret=vNhYGbKJmQPi3X0jT/T7et8z1v4j137L5dg3IITR9XLZJMD0lKWvyaSpYsl0s7vRKYvgdON3MIdATyxBEjvibw==
#time expiration
khiem.jwt.token-validity-in-seconds=86400
# ===============================
# Swagger / OpenAPI
# ===============================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ???ng d?n swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# fix l?i generic response
springdoc.override-with-generic-response=false

# disable petstore default
springdoc.swagger-ui.disable-swagger-default-url=true